--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_CLS_PREMIO_VALID
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" 
   (	"ANNO_CAMPAGNA" NUMBER(10,0), 
	"CODICE_INTERVENTO" VARCHAR2(400 CHAR), 
	"CUAA" VARCHAR2(16 CHAR), 
	"ID_SESSIONE" NUMBER(19,0), 
	"SESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012722
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012722" ON "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" ("ANNO_CAMPAGNA", "CODICE_INTERVENTO", "CUAA", "ID_SESSIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_CLS_PREMIO_VALID
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" MODIFY ("ANNO_CAMPAGNA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" MODIFY ("CODICE_INTERVENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" MODIFY ("CUAA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" MODIFY ("SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" ADD PRIMARY KEY ("ANNO_CAMPAGNA", "CODICE_INTERVENTO", "CUAA", "ID_SESSIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_CLS_PREMIO_VALID
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_T_CLS_PREMIO_VALID" ADD CONSTRAINT "FK5CCRQ9D80M1MY4EJ5BBME8P0F" FOREIGN KEY ("SESSIONE")
	  REFERENCES "ZOOTECNIA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
