--------------------------------------------------------
--  File creato - martedì-aprile-14-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" 
   (	"ID_ALLEVAMENTO" NUMBER(19,0), 
	"ID_CAPO" NUMBER(19,0), 
	"FK_ID_SESSIONE" NUMBER(19,0), 
	"VITELLO_CAPO_ID" NUMBER(19,0), 
	"COD_AZIENDA" VARCHAR2(12 CHAR), 
	"AZIENDA_LATITUDINE" FLOAT(126), 
	"AZIENDA_LONGITUDINE" FLOAT(126), 
	"COD_LIBRO" VARCHAR2(3 CHAR), 
	"CODICE" VARCHAR2(16 CHAR), 
	"CODICE_VITELLO" VARCHAR2(16 CHAR), 
	"CUAA" VARCHAR2(16 CHAR), 
	"DATA_NASCITA" DATE, 
	"DESCR_LIBRO" VARCHAR2(500 CHAR), 
	"DATA_FINE_DETENZIONE" DATE, 
	"DATA_INIZIO_DETENZIONE" DATE, 
	"DATA_NASCITA_VITELLO" DATE, 
	"FLAG_DELEGATO" VARCHAR2(10 CHAR), 
	"FLAG_DELEGATO_INGRESSO_VACCA" VARCHAR2(1 CHAR), 
	"FLAG_DELEGATO_INGRESSO_VITELLO" VARCHAR2(1 CHAR), 
	"FLAG_DELEGATO_NASCITA_VITELLO" VARCHAR2(1 CHAR), 
	"FLAG_IBR" VARCHAR2(1 CHAR), 
	"FLAG_PROROGA_MARCATURA" VARCHAR2(1 CHAR), 
	"FLAG_RISPETTO_PREVALENZA_IBR" VARCHAR2(10 CHAR), 
	"COD_RAZZA" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_INGR_VACCA" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_INGR_VITELLO" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_NASC_VITELLO" VARCHAR2(3 CHAR), 
	"SESSO" VARCHAR2(1 CHAR), 
	"SESSO_VITELLO" VARCHAR2(1 CHAR), 
	"VACCA_DATA_COM_AUT_INGRESSO" DATE, 
	"VACCA_DATA_INGRESSO" DATE, 
	"VACCA_DATA_INSER_BDN_INGRESSO" DATE, 
	"VITELLO_DATA_APPL_MARCHIO" DATE, 
	"VITELLO_DATA_COM_AUT_INGRESSO" DATE, 
	"VITELLO_DATA_COM_AUT_NASCITA" DATE, 
	"VITELLO_DATA_INSER_BDN_NASCITA" DATE, 
	"VITELLO_TIPO_ORIGINE" VARCHAR2(1 CHAR), 
	"VITELLO_DATA_INS_BDN_INGRESSO" DATE, 
	"FK_CODICE_ERRORE_BOVINI" VARCHAR2(400 CHAR), 
	"FK_NUMERO_CAPI_BOVINI" NUMBER(19,0), 
	"FK_ID_SESSIONE_BOVINI" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_TWS_BDN_DU_CAP_BOV" ON "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ("ID_ALLEVAMENTO", "ID_CAPO", "FK_ID_SESSIONE", "VITELLO_CAPO_ID") 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("ID_ALLEVAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("ID_CAPO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("FK_ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("VITELLO_CAPO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ADD CONSTRAINT "FK_DMT_T_SESSIONE_08" FOREIGN KEY ("FK_ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ADD CONSTRAINT "FK_DMT_D_CLS_PR_VAL_RESP_08" FOREIGN KEY ("FK_CODICE_ERRORE_BOVINI", "FK_NUMERO_CAPI_BOVINI", "FK_ID_SESSIONE_BOVINI")
	  REFERENCES "DEMETRA"."DMT_D_CLS_PREMIO_VAL_RESP" ("CODICE_ERRORE", "NUMERO_CAPI", "ID_SESSIONE") ENABLE;
