CREATE TABLE Dmt_t_tws_bdn_du_capi_ovicaprini (
    id_domanda                     DECIMAL(11, 0) NOT NULL,
    id_allevamento                 VARCHAR(25) NOT NULL,
    cod_intervento                 VARCHAR(3) NOT NULL,
    id_capo                        VARCHAR(25) NOT NULL,
    codice                         VARCHAR(16) COMMENT 'Codice dell''auricolare',
    sesso                          VARCHAR(1),
    cod_razza                      VARCHAR(3),
    sco_razza                      VARCHAR(3),
    data_nascita                   DATE,
    data_inizio_detenzione         DATE,
    data_fine_detenzione           DATE,
    data_macellazione              DATE,
    cod_azienda                    VARCHAR(16),
    genotipo                       VARCHAR(50),
    cons_media                     DECIMAL(11, 4) COMMENT 'Media aritmetica dei giorni di presenza del capo rispetto al numero dei giorni dell''anno campagna',
    dt_scarico                     TIMESTAMP(6),
    data_com_macellazione          DATE COMMENT 'Data di comunicazione all autorita competente della macellazione',
    data_inserimento_bdn_macell    DATE COMMENT 'Data di registrazione in BDN della macellazione',
    data_ultimo_prel_profilassi    DATE COMMENT 'Data dell eventuale ultimo prelievo di profilassi effettuato',
    data_com_nascita               DATE COMMENT 'Data di comunicazione all autorita competente della nascita del capo',
    data_inserimento_bdn_nascita   DATE COMMENT 'Data di registrazione in BDN della nascita del capo',
    data_appl_marchio              DATE COMMENT 'Data di identificazione del capo',
    flag_delegato                  VARCHAR(3) COMMENT 'Flag che indica se l allevamento ha conferito delega per operare in BDN',
    cuaa                           VARCHAR(16) COMMENT 'Codice fiscale del richiedente',
    flag_delegato_nascita          VARCHAR(10),
    ruolo_utente_nascita           VARCHAR(10),
	CONSTRAINT tws_bdn_du_capi_ovicaprini_pk PRIMARY KEY (id_domanda, id_allevamento, cod_intervento, id_capo)
)
