--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_W_TZOO_CIRCUITI_QUALITA
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" 
   (	"CUAA" VARCHAR2(16 CHAR), 
	"ID_SESSIONE" NUMBER(19,0), 
	"ID_ALLEV_BDN" VARCHAR2(25 CHAR), 
	"SCO_CAT_CQ" VARCHAR2(3 CHAR), 
	"SCO_DEMON_CQ" VARCHAR2(3 CHAR), 
	"COD_ALLEVAMENTO" VARCHAR2(26 CHAR), 
	"COD_CAT_CQ" VARCHAR2(3 CHAR), 
	"COD_DEMON_CQ" VARCHAR2(3 CHAR), 
	"DATA_FINE" DATE, 
	"DATA_INIZIO" DATE, 
	"PEC_STRUTTURA" VARCHAR2(100 CHAR), 
	"REGIONE_SOCIALE_AZIENDA" VARCHAR2(200 CHAR), 
	"STRUTTURA" VARCHAR2(100 CHAR), 
	"ESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012854
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012854" ON "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" ("CUAA", "ID_SESSIONE", "ID_ALLEV_BDN", "SCO_CAT_CQ", "SCO_DEMON_CQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_W_TZOO_CIRCUITI_QUALITA
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" MODIFY ("CUAA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" MODIFY ("ID_ALLEV_BDN" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" MODIFY ("SCO_CAT_CQ" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" MODIFY ("SCO_DEMON_CQ" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" MODIFY ("ESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" ADD PRIMARY KEY ("CUAA", "ID_SESSIONE", "ID_ALLEV_BDN", "SCO_CAT_CQ", "SCO_DEMON_CQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_W_TZOO_CIRCUITI_QUALITA
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_TZOO_CIRCUITI_QUALITA" ADD CONSTRAINT "FK3EPBXFAQACSG3SELOYNJLI9QX" FOREIGN KEY ("ESSIONE")
	  REFERENCES "ZOOTECNIA"."SESSIONE" ("ID_SESSIONE") ENABLE;
