--------------------------------------------------------
--  File creato - martedì-aprile-14-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_SUBENTRO_ZOO
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_T_SUBENTRO_ZOO" 
   (	"ID_SUBENTRO_ZOO" NUMBER(19,0), 
	"ANNO_CAMPAGNA" NUMBER(10,0), 
	"CUAA_DOMANDA" VARCHAR2(16 CHAR), 
	"CUAA_SUBENTRO" VARCHAR2(16 CHAR), 
	"DATA_FINE" DATE, 
	"DATA_INIZIO" DATE, 
	"EXT_ID_UTENTE_AGGIORNAMENTO" NUMBER(19,0), 
	"NOTE" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMETRA_TBL " ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_SUBENTRO_ZOO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."IE_DMT_T_SUBENTRO_ZOO" ON "ZOOTECNIA"."DMT_T_SUBENTRO_ZOO" ("ID_SUBENTRO_ZOO") 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMETRA_IDX " ;
--------------------------------------------------------
--  Constraints for Table DMT_T_SUBENTRO_ZOO
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_T_SUBENTRO_ZOO" MODIFY ("ID_SUBENTRO_ZOO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_SUBENTRO_ZOO" MODIFY ("CUAA_DOMANDA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_SUBENTRO_ZOO" MODIFY ("CUAA_SUBENTRO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_SUBENTRO_ZOO" ADD CONSTRAINT "PK_DMT_T_SUBENTRO_ZOO" PRIMARY KEY ("ID_SUBENTRO_ZOO")
  USING INDEX
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMETRA_IDX "  ENABLE;
