--------------------------------------------------------
--  File creato - martedì-aprile-14-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" 
   (	"CENSIMENTO_ID" NUMBER(19,2), 
	"P_ALLEV_ID" NUMBER(19,2), 
	"FK_ID_SESSIONE" NUMBER(19,0), 
	"AZIENDA_CODICE" VARCHAR2(400 CHAR), 
	"C_CAPI_TOT" NUMBER(19,2), 
	"C_CAPRETTI_MAC_TOT" NUMBER(19,2), 
	"C_FEMMINE_ADULTE" NUMBER(19,2), 
	"C_FEMMINE_ADULTE_LIB" NUMBER(19,2), 
	"C_FEMMINE_RIMONTA" NUMBER(19,2), 
	"C_FEMMINE_RIMONTA_LIB" NUMBER(19,2), 
	"C_MASCHI_ADULTI" NUMBER(19,2), 
	"C_MASCHI_ADULTI_LIB" NUMBER(19,2), 
	"C_MASCHI_RIMONTA" NUMBER(19,2), 
	"C_MASCHI_RIMONTA_LIB" NUMBER(19,2), 
	"COD_FISCALE_DETE" VARCHAR2(400 CHAR), 
	"COD_FISCALE_PROP" VARCHAR2(400 CHAR), 
	"DATA_CENSIMENTO" DATE, 
	"DATA_FINE_PERIODO" DATE, 
	"DATA_INIZIO_PERIODO" DATE, 
	"DT_COM_AUTORITA" DATE, 
	"O_AGNELLI_MAC_TOT" NUMBER(19,2), 
	"O_CAPI_TOT" NUMBER(19,2), 
	"O_FEMMINE_ADULTE" NUMBER(19,2), 
	"O_FEMMINE_ADULTE_LIB" NUMBER(19,2), 
	"O_FEMMINE_RIMONTA" NUMBER(19,2), 
	"O_FEMMINE_RIMONTA_LIB" NUMBER(19,2), 
	"O_MASCHI_ADULTI" NUMBER(19,2), 
	"O_MASCHI_ADULTI_LIB" NUMBER(19,2), 
	"O_MASCHI_RIMONTA" NUMBER(19,2), 
	"O_MASCHI_RIMONTA_LIB" NUMBER(19,2), 
	"SPECIE_CODICE" VARCHAR2(400 CHAR), 
	"SPECIE_DESCRIZIONE" VARCHAR2(400 CHAR)
   )
  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_UBA_CEN_ALLV_OVN_10" ON "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" ("CENSIMENTO_ID", "P_ALLEV_ID", "FK_ID_SESSIONE") 

  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("CENSIMENTO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("P_ALLEV_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("FK_ID_SESSIONE" NOT NULL ENABLE);
 
  
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" ADD CONSTRAINT "FK_DMT_T_SESSIONE_04" FOREIGN KEY ("FK_ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
