ALTER TABLE DMT_T_TLATTE_MENSILE_ARPEA MODIFY ANNO_RIFERIMENTO NUMBER(4,0);

ALTER TABLE DMT_T_TLATTE_MENSILE_ARPEA MODIFY ANNO_SOLARE NUMBER(4,0);

ALTER TABLE DMT_T_TLATTE_MENSILE_ARPEA MODIFY PRIMO_ANNO_CAMPAGNA NUMBER(4,0);

ALTER TABLE DMT_T_TLATTE_MENSILE_ARPEA MODIFY TEN_MAT_GRASSA_PERIODO NUMBER(6,2);