ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY BUFALINI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CAPI_0_6_MESI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CAPI_6_24_MESI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CAPI_OLTRE_24_MESI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CAPRINI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CONS_MEDIA_CAPI_0_6_MESI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CONS_MEDIA_CAPI_6_24_MESI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CONS_MEDIA_CAPI_OLTRE_24_MESI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CONS_MEDIA_TOTALE NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY CONS_MEDIA_VACCHE_OLTRE_20 NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY OVINI NUMBER(5,2);

ALTER TABLE DMT_T_DS_SCARICO_ALLEVAMENTI MODIFY VACCHE_DA_LATTE NUMBER(5,2);