--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_W_CALCOLI_INTERVENTI
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" 
   (	"ID_GESTORE" NUMBER(19,0), 
	"ID_INTERVENTO" NUMBER(19,0), 
	"ID_SESSIONE" NUMBER(19,0), 
	"ORDINE_ESECUZIONE" VARCHAR2(10 CHAR), 
	"SESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012812
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012812" ON "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" ("ID_GESTORE", "ID_INTERVENTO", "ID_SESSIONE", "ORDINE_ESECUZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_W_CALCOLI_INTERVENTI
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" MODIFY ("ID_GESTORE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" MODIFY ("ID_INTERVENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" MODIFY ("ORDINE_ESECUZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" MODIFY ("SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" ADD PRIMARY KEY ("ID_GESTORE", "ID_INTERVENTO", "ID_SESSIONE", "ORDINE_ESECUZIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_W_CALCOLI_INTERVENTI
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_CALCOLI_INTERVENTI" ADD CONSTRAINT "FKJ7ECDK8539Q4KELBO5YA5DBRG" FOREIGN KEY ("SESSIONE")
	  REFERENCES "ZOOTECNIA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
