--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_W_TDU_PREMIO_CAPI
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" 
   (	"COD_ALLEVAMENTO" VARCHAR2(15 CHAR), 
	"CODICE" VARCHAR2(16 CHAR), 
	"FLG_CONF_PREMIO" VARCHAR2(1 CHAR), 
	"ID_SESSIONE" NUMBER(19,0), 
	"ID_ALLEV_BDN" VARCHAR2(25 CHAR), 
	"ID_AZIENDA" NUMBER(19,0), 
	"VERSIONE" NUMBER(19,0), 
	"SCO_INTERVENTO" VARCHAR2(3 CHAR), 
	"COD_INTERVENTO" VARCHAR2(3 CHAR) DEFAULT 'TPZ', 
	"DATA_FINE_DETENZIONE" DATE, 
	"DATA_INIZIO_DETENZIONE" DATE, 
	"FLG_AMMISSIBILE" VARCHAR2(1 CHAR), 
	"SESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012831
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012831" ON "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" ("COD_ALLEVAMENTO", "CODICE", "FLG_CONF_PREMIO", "ID_SESSIONE", "ID_ALLEV_BDN", "ID_AZIENDA", "VERSIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_W_TDU_PREMIO_CAPI
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("COD_ALLEVAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("CODICE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("FLG_CONF_PREMIO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("ID_ALLEV_BDN" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("ID_AZIENDA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("VERSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("SCO_INTERVENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("DATA_FINE_DETENZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("DATA_INIZIO_DETENZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("FLG_AMMISSIBILE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" MODIFY ("SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" ADD PRIMARY KEY ("COD_ALLEVAMENTO", "CODICE", "FLG_CONF_PREMIO", "ID_SESSIONE", "ID_ALLEV_BDN", "ID_AZIENDA", "VERSIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_W_TDU_PREMIO_CAPI
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_TDU_PREMIO_CAPI" ADD CONSTRAINT "FKS8UIDVA21TB4RT62L4B985HSV" FOREIGN KEY ("SESSIONE")
	  REFERENCES "ZOOTECNIA"."SESSIONE" ("ID_SESSIONE") ENABLE;
