--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_W_TPREMIO_CAPI
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" 
   (	"COD_ALLEVAMENTO" VARCHAR2(15 CHAR), 
	"COD_SPECIE" VARCHAR2(3 CHAR) DEFAULT 'TCA', 
	"ID_SESSIONE" NUMBER(19,0), 
	"ID_ALLEV_BDN" VARCHAR2(25 CHAR), 
	"ID_AZIENDA" NUMBER(19,0), 
	"SCO_SPECIE" VARCHAR2(3 CHAR), 
	"VERSIONE" NUMBER(19,0), 
	"AGNELLE_RIMONTA" VARCHAR2(1 CHAR), 
	"BOVINI_MACELLATI" VARCHAR2(1 CHAR), 
	"BUFALE" VARCHAR2(1 CHAR), 
	"CAP" VARCHAR2(5 CHAR), 
	"COD_ASL" VARCHAR2(16 CHAR), 
	"COD_ISTAT_COM" VARCHAR2(3 CHAR), 
	"COD_ISTAT_PROV" VARCHAR2(3 CHAR), 
	"COD_TITOLARITA" VARCHAR2(3 CHAR) DEFAULT 'TCP', 
	"DATA_SCARICO" TIMESTAMP (6), 
	"DENOMINAZIONE" VARCHAR2(30 CHAR), 
	"FRAZIONE" VARCHAR2(40 CHAR), 
	"ID_FISCALE" VARCHAR2(16 CHAR), 
	"INDIRIZZO" VARCHAR2(100 CHAR), 
	"MACELLATI_12_MESI" VARCHAR2(1 CHAR), 
	"MACELLATI_ETICHETTATURA" VARCHAR2(1 CHAR), 
	"MACELLATI_IGP" VARCHAR2(1 CHAR), 
	"MACELLATI_QUALITA" VARCHAR2(1 CHAR), 
	"OVICAPRINI_MACELLATI" VARCHAR2(1 CHAR), 
	"SCO_TITOLARITA" VARCHAR2(3 CHAR), 
	"TELEFONO" VARCHAR2(20 CHAR), 
	"VACCHE_CARNE_IBR" VARCHAR2(1 CHAR), 
	"VACCHE_LATTE" VARCHAR2(1 CHAR), 
	"VACCHE_MONTAGNA" VARCHAR2(1 CHAR), 
	"VACCHE_NUTRICI" VARCHAR2(1 CHAR), 
	"VACCHE_NUTRICI_DA" VARCHAR2(1 CHAR), 
	"VACCHE_NUTRICI_NG" VARCHAR2(1 CHAR), 
	"SESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012847
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012847" ON "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" ("COD_ALLEVAMENTO", "COD_SPECIE", "ID_SESSIONE", "ID_ALLEV_BDN", "ID_AZIENDA", "SCO_SPECIE", "VERSIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_W_TPREMIO_CAPI
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("COD_ALLEVAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("COD_SPECIE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("ID_ALLEV_BDN" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("ID_AZIENDA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("SCO_SPECIE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("VERSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("COD_ASL" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("COD_ISTAT_COM" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("COD_TITOLARITA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("DATA_SCARICO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("DENOMINAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("INDIRIZZO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("SCO_TITOLARITA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" MODIFY ("SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" ADD PRIMARY KEY ("COD_ALLEVAMENTO", "COD_SPECIE", "ID_SESSIONE", "ID_ALLEV_BDN", "ID_AZIENDA", "SCO_SPECIE", "VERSIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_W_TPREMIO_CAPI
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_TPREMIO_CAPI" ADD CONSTRAINT "FKMULKNRPSH957BLTR78VPRTNNK" FOREIGN KEY ("SESSIONE")
	  REFERENCES "ZOOTECNIA"."SESSIONE" ("ID_SESSIONE") ENABLE;
