--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_TLATTE_VEND_DIR
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" 
   (	"ID_AZIENDA" NUMBER(19,0), 
	"ID_SESSIONE" NUMBER(19,0), 
	"MATRICOLA" NUMBER(19,0), 
	"PROGR_RIGA" NUMBER(19,0), 
	"VERSIONE" NUMBER(19,0), 
	"CODICE_MESE" VARCHAR2(3 CHAR) DEFAULT 'MES', 
	"QUANTITA" NUMBER(19,0), 
	"SOTTO_CODICE_MESE" VARCHAR2(3 CHAR), 
	"SESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012789
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012789" ON "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" ("ID_AZIENDA", "ID_SESSIONE", "MATRICOLA", "PROGR_RIGA", "VERSIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_TLATTE_VEND_DIR
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("ID_AZIENDA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("MATRICOLA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("PROGR_RIGA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("VERSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("CODICE_MESE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("SOTTO_CODICE_MESE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" MODIFY ("SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" ADD PRIMARY KEY ("ID_AZIENDA", "ID_SESSIONE", "MATRICOLA", "PROGR_RIGA", "VERSIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_TLATTE_VEND_DIR
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_T_TLATTE_VEND_DIR" ADD CONSTRAINT "FKB6VNXGC6NW7QDWEUJ2J9HPGNO" FOREIGN KEY ("SESSIONE")
	  REFERENCES "ZOOTECNIA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
