
package it.csi.demetra.demetraws.srmanags.wsbridge2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSBridge2", targetNamespace = "http://it/csi/smranags/wsbridge2/business/wsbridgefacade")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSBridge2 {


    /**
     * 
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response esitoNotificaBiologico()
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getEsitoDomande()
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getTrovaPascoloPac2015(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoEQUIRegistriPascoloCod(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getEsitiRicevutiPAC2015(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param disposizioneTipoVO
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response convalidaRecupero(
        @WebParam(name = "disposizioneTipoVO", partName = "disposizioneTipoVO")
        DisposizioneTipoVO disposizioneTipoVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response invioNotificaBiologico(
        @WebParam(name = "arg0", partName = "arg0")
        WbComunicazioneNotificaVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaAllevamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response invioNuovaNotificaBiologico(
        @WebParam(name = "arg0", partName = "arg0")
        WbComunicazioneNuovaNotificaVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getMovimentazioneTitoli(
        @WebParam(name = "arg0", partName = "arg0")
        WbInputMovimentazioneTitoli arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response annullaComunicazioneRecesso(
        @WebParam(name = "arg0", partName = "arg0")
        WbAnnullaComunicazioneRecessoVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.WbDatiNotificaPerIdentificativoResponse
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public WbDatiNotificaPerIdentificativoResponse datiNotificaPerIdentificativo2(
        @WebParam(name = "arg0", partName = "arg0")
        WbDatiNotificaPerIdentificativoInputVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.VerificaCompensazioneRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public VerificaCompensazioneRispostaVO verificaCompensazioneRND(
        @WebParam(name = "arg0", partName = "arg0")
        VerificaCompensazioneVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.GiustificativoResponse
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public GiustificativoResponse consultazioneDocumentoGiustificativo(
        @WebParam(name = "arg0", partName = "arg0")
        WbConsultazioneDocumentoGiustificativoVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getAnagraficaAllevamenti(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getTitoliProduttorePac2015(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param dataFinePeriodo
     * @param dataInizioPeriodo
     * @param cuaa
     * @param codAzienda
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaAlPascolo(
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "dataInizioPeriodo", partName = "dataInizioPeriodo")
        String dataInizioPeriodo,
        @WebParam(name = "dataFinePeriodo", partName = "dataFinePeriodo")
        String dataFinePeriodo,
        @WebParam(name = "codAzienda", partName = "codAzienda")
        String codAzienda)
        throws Exception_Exception
    ;

    /**
     * 
     * @param disposizioneTipoVO
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response annullaRecupero(
        @WebParam(name = "disposizioneTipoVO", partName = "disposizioneTipoVO")
        DisposizioneTipoVO disposizioneTipoVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param dataFinePeriodo
     * @param dataInizioPeriodo
     * @param tipoResponsabilita
     * @param cuaa
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod(action = "/wsbridge2/WSBridgeService/WSBridge2/getConsistenzaUbaCensimOvini2012")
    @WebResult(partName = "return")
    public Response getConsistenzaUbaCensimOvini2012(
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "dataInizioPeriodo", partName = "dataInizioPeriodo")
        String dataInizioPeriodo,
        @WebParam(name = "dataFinePeriodo", partName = "dataFinePeriodo")
        String dataFinePeriodo,
        @WebParam(name = "tipoResponsabilita", partName = "tipoResponsabilita")
        String tipoResponsabilita)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param dataFinePeriodo
     * @param dataInizioPeriodo
     * @param cuaa
     * @param codAzienda
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaAlPascoloDal2014(
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "dataInizioPeriodo", partName = "dataInizioPeriodo")
        String dataInizioPeriodo,
        @WebParam(name = "dataFinePeriodo", partName = "dataFinePeriodo")
        String dataFinePeriodo,
        @WebParam(name = "codAzienda", partName = "codAzienda")
        String codAzienda)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.FinalizzazioneCompensazioneRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public FinalizzazioneCompensazioneRispostaVO finalizzazioneCompensazioneRND(
        @WebParam(name = "arg0", partName = "arg0")
        FinalizzazioneCompensazioneVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.RecuperaRisultatoCompensazioniAsincroneRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public RecuperaRisultatoCompensazioniAsincroneRispostaVO recuperaRisultatoCompensazioniAsincroneRND(
        @WebParam(name = "arg0", partName = "arg0")
        RecuperaRisultatoCompensazioniAsincroneVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.RichiestaCompensazioniAsincroneRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public RichiestaCompensazioniAsincroneRispostaVO richiestaCompensazioniAsincroneRND(
        @WebParam(name = "arg0", partName = "arg0")
        RichiestaCompensazioniAsincroneVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoOVIRegistriPascoloCodPeriodoDeten(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaStatisticaMediaAllevamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoRegistriPascoloCodPeriodoDeten(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoEQUIRegistriPascoloCodDeten(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param campagna
     * @param cuaa
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response quoteLatteGisTa10(
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "campagna", partName = "campagna")
        String campagna)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getMovimentazioneTitoliPAC2015(
        @WebParam(name = "arg0", partName = "arg0")
        WbInputMovimentazioneTitoli arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.IterResponse
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public IterResponse consultazioneIterAmministrativo(
        @WebParam(name = "arg0", partName = "arg0")
        WbConsultazioneIterAmministrativoVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param ordinamento
     * @param tipo
     * @param aziendaCodice
     * @param allevIdFiscale
     * @param speCodice
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.ElencoOviRegistriStallaCodResponseVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ElencoOviRegistriStallaCodResponseVO getElencoOviRegistriStallaCod(
        @WebParam(name = "aziendaCodice", partName = "aziendaCodice")
        String aziendaCodice,
        @WebParam(name = "speCodice", partName = "speCodice")
        String speCodice,
        @WebParam(name = "allevIdFiscale", partName = "allevIdFiscale")
        String allevIdFiscale,
        @WebParam(name = "tipo", partName = "tipo")
        String tipo,
        @WebParam(name = "ordinamento", partName = "ordinamento")
        String ordinamento)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getEsitoDomandePAC2015()
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaAllevamentoAperto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response confermaLetturaIdNotifica(
        @WebParam(name = "arg0", partName = "arg0")
        WbInputSIBIdNotificaVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getTitoliProduttore(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaAlPascoloPac2015(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getTitoliProduttoreAggregatiPac2015(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param ordinamento
     * @param tipo
     * @param aziendaCodice
     * @param allevIdFiscale
     * @param speCodice
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.ElencoRegistriStallaCodResponseVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ElencoRegistriStallaCodResponseVO getElencoRegistriStallaCod(
        @WebParam(name = "aziendaCodice", partName = "aziendaCodice")
        String aziendaCodice,
        @WebParam(name = "speCodice", partName = "speCodice")
        String speCodice,
        @WebParam(name = "allevIdFiscale", partName = "allevIdFiscale")
        String allevIdFiscale,
        @WebParam(name = "tipo", partName = "tipo")
        String tipo,
        @WebParam(name = "ordinamento", partName = "ordinamento")
        String ordinamento)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response invioNotificaPregressaBiologico(
        @WebParam(name = "arg0", partName = "arg0")
        WbComunicazNotificaPregrVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getAnomaliePerCUAADU10(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        StringArray arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.AnnullamentoCompensazioneRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public AnnullamentoCompensazioneRispostaVO annullamentoCompensazioneRND(
        @WebParam(name = "arg0", partName = "arg0")
        AnnullamentoCompensazioneVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoRegistriPascoloCodPeriodo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param etichettaTypeVO
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.ElencoRecuperiResponseVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public ElencoRecuperiResponseVO prelevaRecupero(
        @WebParam(name = "etichettaTypeVO", partName = "etichettaTypeVO")
        EtichettaTypeVO etichettaTypeVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getListaUsciteDaPascoloPartiteOvini(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.IswsResponseAnomalieAsrVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public IswsResponseAnomalieAsrVO anomaliePerCUAAPSR(
        @WebParam(name = "arg0", partName = "arg0")
        IswsAnomaliePerCuaaVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoOVIRegistriPascoloCodPeriodo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getListaCUAAConAnomalieDU10(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean testResources();

    /**
     * 
     * @param richiestaRegistraRecuperoInputVO
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response registraRecupero(
        @WebParam(name = "richiestaRegistraRecuperoInputVO", partName = "richiestaRegistraRecuperoInputVO")
        RichiestaRegistraRecuperoInputVO richiestaRegistraRecuperoInputVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.RiepilogoFondoRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public RiepilogoFondoRispostaVO riepilogoFondoRND(
        @WebParam(name = "arg0", partName = "arg0")
        RiepilogoFondoVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoRegistriPascoloCodDeten(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getListaIngressiAlPascoloPartiteOvini(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.WbElencoIdNotificheAggiornateCuaaResponse
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public WbElencoIdNotificheAggiornateCuaaResponse elencoIdNotificheAggiornateCuaa(
        @WebParam(name = "arg0", partName = "arg0")
        WbElencoIdNotificheAggiornateCuaaInputVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param idRegistraRecuperoVO
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.RispostaRichiestaIdResponseVO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public RispostaRichiestaIdResponseVO getIdRegistrazione(
        @WebParam(name = "idRegistraRecuperoVO", partName = "idRegistraRecuperoVO")
        IdRegistraRecuperoVO idRegistraRecuperoVO)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getGiacenzePerDichiarazione(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.WbIstruttoriaOdcResponse
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public WbIstruttoriaOdcResponse consultazioneEsitoIstruttoriaOdc(
        @WebParam(name = "arg0", partName = "arg0")
        WbConsultazioneEsitoIstruttoriaOdcInputVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response listaCodICQRF(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response comunicazioneEsitoIstruttoria(
        @WebParam(name = "arg0", partName = "arg0")
        WbComunicazioneEsitoIstruttoriaVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getElencoCapiPremio(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response trovaFascicoloFS50(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param codiceIntervento
     * @param annoCampagna
     * @param cuaa
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod(action = "/wsbridge2/WSBridgeService/WSBridge2/getElencoCapiPremioNew")
    @WebResult(partName = "return")
    public Response getElencoCapiPremioNew(
        @WebParam(name = "codiceIntervento", partName = "codiceIntervento")
        String codiceIntervento,
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "annoCampagna", partName = "annoCampagna")
        int annoCampagna)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response trovaFascicoloFS6(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response cancellaComunicazioneNuovaNotifica(
        @WebParam(name = "arg0", partName = "arg0")
        WbCancellaComunicazioneVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getEsitiRicevuti(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param dataFinePeriodo
     * @param dataInizioPeriodo
     * @param tipoResponsabilita
     * @param cuaa
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response getConsistenzaUbaOvini(
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "dataInizioPeriodo", partName = "dataInizioPeriodo")
        String dataInizioPeriodo,
        @WebParam(name = "dataFinePeriodo", partName = "dataFinePeriodo")
        String dataFinePeriodo,
        @WebParam(name = "tipoResponsabilita", partName = "tipoResponsabilita")
        String tipoResponsabilita)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.RichiestaCompensazioneRispostaVO
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public RichiestaCompensazioneRispostaVO richiestaCompensazioneRND(
        @WebParam(name = "arg0", partName = "arg0")
        RichiestaCompensazioneVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response comunicazioneRecesso(
        @WebParam(name = "arg0", partName = "arg0")
        WbComunicazioneRecessoVO arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public Response confermaLetturaEsitoBiologico(
        @WebParam(name = "arg0", partName = "arg0")
        WbConfermaLetturaEsitoVO arg0)
        throws WSBridgeInternalException_Exception
    ;

    /**
     * 
     * @param idAlleBdn
     * @param codiceIntervento
     * @param cuaa2
     * @param annoCampagna
     * @param cuaa
     * @return
     *     returns it.csi.demetra.demetraws.srmanags.wsbridge2.Response
     * @throws WSBridgeInternalException_Exception
     */
    @WebMethod(action = "/wsbridge2/WSBridgeService/WSBridge2/getElencoCapiPremio2New")
    @WebResult(partName = "return")
    public Response getElencoCapiPremio2New(
        @WebParam(name = "idAlleBdn", partName = "idAlleBdn")
        long idAlleBdn,
        @WebParam(name = "codiceIntervento", partName = "codiceIntervento")
        String codiceIntervento,
        @WebParam(name = "cuaa", partName = "cuaa")
        String cuaa,
        @WebParam(name = "cuaa2", partName = "cuaa2")
        String cuaa2,
        @WebParam(name = "annoCampagna", partName = "annoCampagna")
        int annoCampagna)
        throws WSBridgeInternalException_Exception
    ;

}
