--------------------------------------------------------
--  File creato - mercoledì-giugno-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_DS_SCARICO_ALLEVAMENTI
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_DS_SCARICO_ALLEVAMENTI" 
   (	"ALLEV_ID" NUMBER(10,0), 
	"AUTORIZZAZIONE_LATTE" VARCHAR2(1 CHAR), 
	"AZIENDA_CODICE" VARCHAR2(12 CHAR), 
	"BUFALINI" NUMBER(*,2), 
	"CAP" VARCHAR2(5 CHAR), 
	"CAPI_0_6_MESI" NUMBER(*,2), 
	"CAPI_6_24_MESI" NUMBER(*,2), 
	"CAPI_OLTRE_24_MESI" NUMBER(*,2), 
	"CAPI_TOTALI" NUMBER(19,2), 
	"CAPRINI" NUMBER(*,2), 
	"COD_FISCALE_PROP" VARCHAR2(16 CHAR), 
	"COD_TIPO_ALLEV" VARCHAR2(10 CHAR), 
	"CODICE_FISCALE_DETEN" VARCHAR2(16 CHAR), 
	"COM_CODICE" VARCHAR2(6 CHAR), 
	"CONS_MEDIA_CAPI_0_6_MESI" NUMBER(*,2), 
	"CONS_MEDIA_CAPI_6_24_MESI" NUMBER(*,2), 
	"CONS_MEDIA_CAPI_OLTRE_24_MESI" NUMBER(*,2), 
	"CONS_MEDIA_TOTALE" NUMBER(*,2), 
	"CONS_MEDIA_VACCHE_OLTRE_20" NUMBER(*,2), 
	"DATA_CALCOLO_CAPI" DATE, 
	"DATA_INIZIO_AUTORIZZAZIONE" DATE, 
	"DATA_REVOCA_AUTORIZZAZIONE" DATE, 
	"DATA_ULTIMO_CENSIMENTO" DATE, 
	"DENOM_DETENTORE" VARCHAR2(50 CHAR), 
	"DENOM_PROPRIETARIO" VARCHAR2(50 CHAR), 
	"DENOMINAZIONE" VARCHAR2(50 CHAR), 
	"DESCR_TIPO_ALLEV" VARCHAR2(255 CHAR), 
	"DT_FINE_ATTIVITA" DATE, 
	"DT_FINE_DETENTORE" DATE, 
	"DT_FINE_PERIODO" DATE, 
	"DT_INIZIO_ATTIVITA" DATE, 
	"DT_INIZIO_DETENTORE" DATE, 
	"DT_INIZIO_PERIODO" DATE, 
	"FLAG_LIBRI_GENEALOGICI" VARCHAR2(1 CHAR), 
	"FOGLIO_CATASTALE" VARCHAR2(10 CHAR), 
	"ID_FISCALE" VARCHAR2(16 CHAR), 
	"INDIRIZZO" VARCHAR2(50 CHAR), 
	"LATITUDINE" NUMBER(11,6), 
	"LOCALITA" VARCHAR2(50 CHAR), 
	"LONGITUDINE" NUMBER(11,6), 
	"ORIENTAMENTO_PRODUTTIVO" VARCHAR2(10 CHAR), 
	"OVINI" NUMBER(*,2), 
	"PARTICELLA" VARCHAR2(10 CHAR), 
	"PRO_CODICE" VARCHAR2(6 CHAR), 
	"SEZIONE" VARCHAR2(10 CHAR), 
	"SOCCIDA" VARCHAR2(1 CHAR), 
	"SPE_CODICE" VARCHAR2(10 CHAR), 
	"SUBALTERNO" VARCHAR2(10 CHAR), 
	"TIPO_PRODUZIONE" VARCHAR2(10 CHAR), 
	"VACCHE_DA_LATTE" NUMBER(*,2), 
	"ID_SESSIONE" NUMBER(19,0)
   ) 

  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_DS_SCARICO_ALLEVAMENTI
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_DS_SCARICO_ALLEVAMENTI" ON "DEMETRA"."DMT_T_DS_SCARICO_ALLEVAMENTI" ("ALLEV_ID") 

  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_DS_SCARICO_ALLEVAMENTI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_DS_SCARICO_ALLEVAMENTI" MODIFY ("ALLEV_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_DS_SCARICO_ALLEVAMENTI" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_DS_SCARICO_ALLEVAMENTI" ADD CONSTRAINT "PK_DMT_T_DS_SCA_ALLEV" PRIMARY KEY ("ALLEV_ID");
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_DS_SCARICO_ALLEVAMENTI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_DS_SCARICO_ALLEVAMENTI" ADD CONSTRAINT "FK_DMT_T_SESSIONE_24" FOREIGN KEY ("ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
