--------------------------------------------------------
--  File creato - mercoledì-giugno-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_D_TRIEP_DU_PREMI_CAPI
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" 
   (	"COD_PREMIO" VARCHAR2(3 CHAR), 
	"ID_DOMANDA" NUMBER(19,0), 
	"ID_RICHIESTA" NUMBER(19,0) DEFAULT '0', 
	"SCO_ATTIVITA" VARCHAR2(3 CHAR), 
	"ID_SESSIONE" NUMBER(19,0), 
	"CAPI_ANOMALI_ART52" FLOAT(126), 
	"COD_ATTIVITA" VARCHAR2(3 CHAR) DEFAULT 'TAT', 
	"COD_TIPO_CALCOLO" VARCHAR2(3 CHAR) DEFAULT 'CLC', 
	"DATA_CALCOLO" TIMESTAMP (6), 
	"ESITO_PERC_ART52" FLOAT(126), 
	"ID_AZIENDA" NUMBER(19,0), 
	"IMP_ANTE_MODULAZIONE" FLOAT(126), 
	"IMP_POST_DF" FLOAT(126), 
	"IMP_POST_MODULAZIONE" FLOAT(126), 
	"IMP_POST_PRES_TARD" FLOAT(126), 
	"IMPORTO" FLOAT(126), 
	"IMPORTO_BASE" FLOAT(126), 
	"IMPORTO_PRE_TAGLIO" FLOAT(126), 
	"NR_CAPI_AMM_CAMP" FLOAT(126), 
	"NR_CAPI_ANOMALI_BDN" NUMBER(19,0), 
	"NR_CAPI_ANOMALI_CIL" NUMBER(19,0), 
	"NR_CAPI_BO" NUMBER(19,0), 
	"NR_CAPI_COMP" NUMBER(19,0), 
	"NR_CAPI_CORR" FLOAT(126), 
	"NR_CAPI_LG" NUMBER(19,0), 
	"NR_CAPI_MA" NUMBER(19,0), 
	"NR_CAPI_TOT_BDN" FLOAT(126), 
	"NR_CAPI_TOT_CIL" NUMBER(19,0), 
	"NR_CAPI_VN" NUMBER(19,0), 
	"NR_CAPI_VN2" NUMBER(19,0), 
	"PERC_BASE" FLOAT(126), 
	"PERC_CONDIZIONALITA" FLOAT(126), 
	"PERC_MODULAZIONE" FLOAT(126), 
	"PERC_PAS_FOR" FLOAT(126), 
	"PERC_PRESENT_TARD" FLOAT(126), 
	"PERC_UBA_SAU" FLOAT(126), 
	"SCO_TIPO_CALCOLO" VARCHAR2(3 CHAR) DEFAULT '002', 
	"SCOSTAMENTO_PERC" FLOAT(126), 
	"TIPO_RIGA" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_D_TRIEP_DU_PREMI_CAPI
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_D_TRIEP_DU_PREMI_CAPI" ON "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" ("COD_PREMIO", "ID_DOMANDA", "ID_RICHIESTA", "SCO_ATTIVITA", "ID_SESSIONE") 
  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_D_TRIEP_DU_PREMI_CAPI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("COD_PREMIO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("ID_DOMANDA" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("ID_RICHIESTA" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("SCO_ATTIVITA" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("COD_ATTIVITA" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("COD_TIPO_CALCOLO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("ID_AZIENDA" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("SCO_TIPO_CALCOLO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" MODIFY ("TIPO_RIGA" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" ADD CONSTRAINT "PK_DMT_D_TRIEP_DU_PREMI_CAPI" PRIMARY KEY ("COD_PREMIO", "ID_DOMANDA", "ID_RICHIESTA", "SCO_ATTIVITA", "ID_SESSIONE");
--------------------------------------------------------
--  Ref Constraints for Table DMT_D_TRIEP_DU_PREMI_CAPI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_D_TRIEP_DU_PREMI_CAPI" ADD CONSTRAINT "FK_DMT_T_SESSIONE_02" FOREIGN KEY ("ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
