
package it.csi.demetra.demetraws.srmanags.wsbridge2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WSBridgeInternalException", targetNamespace = "http://it/csi/smranags/wsbridge2/business/wsbridgefacade")
public class WSBridgeInternalException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WSBridgeInternalException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSBridgeInternalException_Exception(String message, WSBridgeInternalException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSBridgeInternalException_Exception(String message, WSBridgeInternalException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.csi.demetra.demetraws.srmanags.wsbridge2.WSBridgeInternalException
     */
    public WSBridgeInternalException getFaultInfo() {
        return faultInfo;
    }

}
