--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_W_CONTR_PREAM
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" 
   (	"ID_INTERVENTO" NUMBER(19,0), 
	"ID_SESSIONE" NUMBER(19,0), 
	"NOME_CLASSE_CALCOLO" VARCHAR2(30 CHAR), 
	"ORDINE_ESECUZIONE" VARCHAR2(10 CHAR), 
	"SESSIONE" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012818
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012818" ON "ZOOTECNIA"."DMT_W_CONTR_PREAM" ("ID_INTERVENTO", "ID_SESSIONE", "NOME_CLASSE_CALCOLO", "ORDINE_ESECUZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DMT_W_CONTR_PREAM
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" MODIFY ("ID_INTERVENTO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" MODIFY ("NOME_CLASSE_CALCOLO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" MODIFY ("ORDINE_ESECUZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" MODIFY ("SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" ADD PRIMARY KEY ("ID_INTERVENTO", "ID_SESSIONE", "NOME_CLASSE_CALCOLO", "ORDINE_ESECUZIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DMT_W_CONTR_PREAM
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."DMT_W_CONTR_PREAM" ADD CONSTRAINT "FKTE1EMFBFBHQUXP4HXG7YNN1Y8" FOREIGN KEY ("SESSIONE")
	  REFERENCES "ZOOTECNIA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
