CREATE TABLE Dmt_w_tpremio_zoo (
    id_azienda                DECIMAL(11, 0) NOT NULL COMMENT 'Rif azienda',
    versione                  DECIMAL(11, 0) NOT NULL COMMENT 'Versione',
    cod_allevamento           VARCHAR(15 ) NOT NULL COMMENT 'Codice allevamento BDN',
    id_allev_bdn              VARCHAR(25 ) NOT NULL COMMENT 'ID allevamento BDN',
    sco_specie                VARCHAR(3 ) NOT NULL COMMENT 'Codice specie',
    cod_specie                VARCHAR(3 ) DEFAULT 'TCA' NOT NULL COMMENT 'Sottocodice specie',
    denominazione             VARCHAR(30 ) NOT NULL COMMENT 'Denominazione',
    cod_titolarita            VARCHAR(3 ) DEFAULT 'TCP' NOT NULL COMMENT 'Codice Titolarità',
    sco_titolarita            VARCHAR(3 ) NOT NULL COMMENT 'Sottocodice titolarità',
    indirizzo                 VARCHAR(100 ) NOT NULL COMMENT 'Indirizzo',
    frazione                  VARCHAR(40 )  COMMENT 'Frazione',
    cod_istat_prov            VARCHAR(3 )  COMMENT 'Provincia',
    cod_istat_com             VARCHAR(3 ) NOT NULL COMMENT 'Comune',
    cap                       VARCHAR(5 )  COMMENT 'CAP',
    telefono                  VARCHAR(20 )  COMMENT 'Telefono',
    cod_asl                   VARCHAR(16 ) NOT NULL COMMENT 'Codice ASL',
    data_scarico              TIMESTAMP(6) NOT NULL COMMENT 'Data scarico da BDN',
    id_fiscale                VARCHAR(16 )  COMMENT 'Id Fiscale da BDN',
    vacche_latte              VARCHAR(1 )  COMMENT 'Premio Vacche da Latte (art. 20)',
    vacche_montagna           VARCHAR(1 )  COMMENT 'Premio Aggiuntivo Vacche da Latte, presenti per almeno 6 mesi in zone montane (art. 20)',
    bufale                    VARCHAR(1 )  COMMENT 'Premio Bufale (art. 20)',
    vacche_nutrici            VARCHAR(1 )  COMMENT 'Premio Vacche nutrici da carne (art. 21)',
    vacche_nutrici_da         VARCHAR(1 )  COMMENT 'Premio Vacche nutrici a duplice attitudine (art. 21)',
    vacche_carne_ibr          VARCHAR(1 )  COMMENT 'Premio Aggiuntivo vacche nutrici di allevamenti che aderiscono a piani di gestione della razza finalizzati al risanamento dal virus responsabile della IBR (art. 21)',
    bovini_macellati          VARCHAR(1 )  COMMENT 'Premio Bovini macellati di almeno 6 mesi  (art. 21)',
    macellati_12_mesi         VARCHAR(1 )  COMMENT 'Premio Aggiuntivo Bovini macellati di almeno 12 mesi  (art. 21)',
    macellati_qualita         VARCHAR(1 )  COMMENT 'Premio Aggiuntivo Bovini macellati aderenti a sistemi di qualità nazionale o regionale (art. 21)',
    macellati_etichettatura   VARCHAR(1 )  COMMENT 'Premio Aggiuntivo Bovini macellati allevati in conformità ad un disciplinare di etichettatura facoltativa approvato dal Mipaaf (art. 21)',
    macellati_igp             VARCHAR(1 )  COMMENT 'Premio Aggiuntivo Bovini macellati certificati ai sensi del reg. UE 1151/2012 (art. 21)',
    agnelle_rimonta           VARCHAR(1 )  COMMENT 'Premio Agnelle da rimonta',
    ovicaprini_macellati      VARCHAR(1 )  COMMENT 'Premio Capi Ovini e Caprini macellati',
    vacche_nutrici_ng         VARCHAR(1 )  COMMENT 'Premio Vacche nutrici non iscritte nei Libri genialogici o registro anagrafico - premio 322',
	CONSTRAINT tpremio_zoo_pk PRIMARY KEY (id_azienda, versione, cod_allevamento, id_allev_bdn, sco_specie,cod_specie)
)