
  CREATE TABLE "ZOOTECNIA"."DMT_T_AGNELLE_RIMONTA" 
   (	"CUAA" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"FK_ID_SESSIONE" NUMBER(19,0) NOT NULL ENABLE, 
	"CODICE_INTERVENTO" VARCHAR2(400 CHAR) NOT NULL ENABLE, 
	"ANNO_CAMPAGNA" NUMBER(10,0) NOT NULL ENABLE, 
	"ESITO" VARCHAR2(255 CHAR), 
	"MOTIVAZIONI" VARCHAR2(1000 CHAR), 
	"QT_CAPI_PREMIO" FLOAT(126)
   ) 
 TABLESPACE "DEMETRA_TBL" ;

  
  ALTER TABLE "ZOOTECNIA"."DMT_T_AGNELLE_RIMONTA" ADD CONSTRAINT "PK_DMT_T_AGNELLE_RIMONTA"  PRIMARY KEY ("CUAA", "FK_ID_SESSIONE");
  ALTER TABLE "ZOOTECNIA"."DMT_T_AGNELLE_RIMONTA" ADD CONSTRAINT "FK_DMT_T_AGNELLE_RIMONTA_01" FOREIGN KEY ("FK_ID_SESSIONE") REFERENCES "ZOOTECNIA"."DMT_S_SESSIONE" ("ID_SESSIONE") ENABLE;

  
   
CREATE UNIQUE INDEX "ZOOTECNIA"."IDX_DMT_T_AGNELLE_RIMONTA_01" ON "ZOOTECNIA"."DMT_T_AGNELLE_RIMONTA" ("CUAA", "FK_ID_SESSIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMETRA_IDX" ;
