CREATE TABLE Dmt_t_tws_bdn_du_capi_bovini (
    id_domanda                       DECIMAL(11, 0) NOT NULL,
    id_allevamento                   VARCHAR(10 ) NOT NULL,
    cod_intervento                   VARCHAR(3 ) NOT NULL,
    id_capo                          VARCHAR(10 ) NOT NULL COMMENT 'Identificativo univoco in BDN del capo bovino',
    cod_vitello                      VARCHAR(14 ) NOT NULL COMMENT 'Codice identificativo del vitello',
    sesso_vitello                    VARCHAR(1 ) COMMENT 'Sesso del vitello',
    codice                           VARCHAR(16 ) COMMENT 'Codice della marca auricolare applicata al capo bovino',
    cod_libro                        VARCHAR(3 ) COMMENT 'Codice del libro genealogico se iscritta',
    descr_libro                      VARCHAR(500 ) COMMENT 'Denominazione del libro genealogico se iscritta',
    data_nascita                     DATE COMMENT 'Data di nascita del capo',
    data_nascita_vitello             DATE COMMENT 'Data di nascita del vitello',
    cod_razza                        VARCHAR(3 ) COMMENT 'Codice della razza della vacca',
    sco_razza                        VARCHAR(3 ),
    data_inizio_detenzione           DATE COMMENT 'Data di inizio detenzione. E valorizzata solo se il capo deve verificare in BDN un periodo minimo di detenzione',
    data_fine_detenzione             DATE COMMENT 'Data di fine detenzione. A partire dalla campagna 2010 è valorizzata solo se il capo deve verificare in BDN un periodo minimo di detenzione',
    cod_azienda                      VARCHAR(12 )  COMMENT 'Codice dell''azienda presso cui è nato il vitello',
    azienda_longitudine              DECIMAL(11, 4) COMMENT 'Longitudine dell azienda',
    azienda_latitudine               DECIMAL(11, 4)COMMENT 'Latitudine dell azienda',
    flag_ibr                         VARCHAR(1 ) COMMENT 'Flag che indica se l azienda aderisce o meno, per l anno di campagna, a piani di risanamento per la IBR',
    flag_rispetto_prevalenza_ibr     VARCHAR(10 ) COMMENT 'Flag che indica se l allevamento ha rispettato o meno  l obiettivo prefissato per il rispetto della sieroprevalenza per lâ€™anno di riferimento.',
    vacca_data_ingresso              DATE COMMENT 'Data di ingresso in stalla del capo',
    vacca_data_com_aut_ingresso      DATE COMMENT 'Data di comunicazione all autorita competente dellâ€™ingresso',
    vacca_data_inser_bdn_ingresso    DATE COMMENT 'Data di registrazione dell ingresso in BDN',
    vitello_data_appl_marchio        DATE COMMENT 'Data di identificazione del vitello',
    vitello_data_com_aut_nascita     DATE COMMENT 'Data di comunicazione all autorita competente della nascita del vitello',
    vitello_data_inser_bdn_nascita   DATE COMMENT 'Data di registrazione in BDN della nascita del capo',
    flag_proroga_marcatura           VARCHAR(10 ) COMMENT 'Flag che indica se l allevamento e o meno autorizzato a prorogare la marcatura dei capi entro 180 giorni dalla nascita',
    cuaa                             VARCHAR(16 ) COMMENT 'Codice fiscale del richiedente',
    sesso                            VARCHAR(10 ) COMMENT 'Sesso del capo madre',
    vitello_capo_id                  VARCHAR(16 ) COMMENT 'Identificativo univoco in BDN del vitello',
    vitello_tipo_origine             VARCHAR(1 ) CHECK(vitello_tipo_origine = 'N' OR vitello_tipo_origine = 'W') COMMENT 'Flag che indica il tipo origine del vitello. N = nato in stella , W = nato in stalla da parto gemellare',
    vitello_data_com_aut_ingresso    DATE COMMENT 	'Data di comunicazione allâ€™autorita competente dell ingresso in stalla del vitello. Essendo nato in stalla coincide con la comunicazione della data di nascita',
    vitello_data_ins_bdn_ingresso    DATE COMMENT 'Data di registrazione dell ingresso in stalla del vitello. Essendo nato in stalla coincide con la data di registrazione della nascita.',
    flag_delegato                    VARCHAR(10 ) COMMENT 'Flag che indica se l allevamento ha conferito delega per operare in BDN.',
    flag_delegato_ingresso_vacca     VARCHAR(10 ),
    ruolo_utente_ingresso_vacca      VARCHAR(10 ),
    flag_delegato_nascita_vitello    VARCHAR(10 ),
    ruolo_utente_nascita_vitello     VARCHAR(10 ),
    flag_delegato_ingresso_vitello   VARCHAR(10 ),
    ruolo_utente_ingresso_vitello    VARCHAR(10 ),
	CONSTRAINT tws_bdn_du_capi_bovini_pk PRIMARY KEY (id_domanda, id_allevamento, cod_intervento, id_capo, cod_vitello)
	)