CREATE TABLE Dmt_d_triep_du_premi_capi (
    id_domanda             INT NOT NULL,
    id_azienda             INT NOT NULL,
    cod_attivita           VARCHAR(3 ) DEFAULT 'TAT' NOT NULL,
    sco_attivita           VARCHAR(3 ) NOT NULL,
    id_richiesta           INT DEFAULT 0 NOT NULL,
    tipo_riga              INT NOT NULL,
    cod_premio             VARCHAR(3 ) NOT NULL,
    importo_base           DECIMAL(12, 2),
    perc_base              DECIMAL(7, 6),
    perc_present_tard      DECIMAL(7, 6),
    imp_ante_modulazione   DECIMAL(12, 2),
    perc_modulazione       DECIMAL(7, 6),
    imp_post_modulazione   DECIMAL(12, 2),
    perc_condizionalita    DECIMAL(7, 6),
    nr_capi_comp           INT,
    nr_capi_corr           DECIMAL(11, 2),
    nr_capi_tot_bdn        DECIMAL(10, 3),
    nr_capi_anomali_bdn    INT,
    nr_capi_tot_cil        INT,
    nr_capi_anomali_cil    INT,
    nr_capi_vn             INT,
    nr_capi_vn2            INT,
    nr_capi_lg             INT,
    nr_capi_bo             INT,
    nr_capi_ma             INT,
    perc_uba_sau           DECIMAL(10, 6),
    perc_pas_for           DECIMAL(7, 6),
    importo                DECIMAL(12, 2),
    cod_tipo_calcolo       VARCHAR(3 ) DEFAULT 'CLC' NOT NULL,
    sco_tipo_calcolo       VARCHAR(3 ) DEFAULT '002' NOT NULL,
    data_calcolo           TIMESTAMP(6),
    imp_post_pres_tard     DECIMAL(12, 2),
    imp_post_df            DECIMAL(12, 2) COMMENT 'Importo al netto della trattenuta per  Disciplina Finanziaria',
    nr_capi_amm_camp       DECIMAL(14, 2) COMMENT 'utilizzato per salvare il numero di capi ammissibili nel caso di domanda a campione',
    importo_pre_taglio     DECIMAL(12, 2) COMMENT 'importo antecedente al riproporzionamento del piccolo agricoltore se l''importo totale dei premi e'' superiore ad un determinato importo',
    esito_perc_art52       DECIMAL(11, 4) COMMENT 'Esito percentuale calcolato sulla misura',
    capi_anomali_art52     DECIMAL(11, 4) COMMENT 'Numero di capi anomali calcolati sulla misura',
    scostamento_perc       DECIMAL(11, 2) COMMENT 'Scostamento calcolato sulla misura',
	CONSTRAINT 	sys_c00356915 PRIMARY KEY (id_domanda, id_richiesta, sco_attivita, tipo_riga, cod_premio,sco_tipo_calcolo)
)