--------------------------------------------------------
--  File creato - giovedì-aprile-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RPU_V_PRATICA_ZOOTE
--------------------------------------------------------

  CREATE TABLE "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" 
   (	"ANNO_CAMPAGNA" NUMBER(10,0), 
	"CODICE_PREMIO" VARCHAR2(255 CHAR), 
	"CUAA" VARCHAR2(16 CHAR), 
	"CODICE_MISURA" VARCHAR2(255 CHAR), 
	"DENOMINAZIONE" VARCHAR2(50 CHAR), 
	"DESCRIZIONE" VARCHAR2(400 CHAR), 
	"EXT_ID_AZIENDA" NUMBER(10,0), 
	"ID_FASE_AVANZAMENTO" NUMBER(10,0), 
	"ID_PRATICA" NUMBER(10,0), 
	"ID_STATO_PRATICA" NUMBER(10,0), 
	"IDENTIFICATIVO" NUMBER(19,0), 
	"TIPO_FASE" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012865
--------------------------------------------------------

  CREATE UNIQUE INDEX "ZOOTECNIA"."SYS_C0012865" ON "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" ("ANNO_CAMPAGNA", "CODICE_PREMIO", "CUAA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RPU_V_PRATICA_ZOOTE
--------------------------------------------------------

  ALTER TABLE "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" MODIFY ("ANNO_CAMPAGNA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" MODIFY ("CODICE_PREMIO" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" MODIFY ("CUAA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" MODIFY ("CODICE_MISURA" NOT NULL ENABLE);
 
  ALTER TABLE "ZOOTECNIA"."RPU_V_PRATICA_ZOOTE" ADD PRIMARY KEY ("ANNO_CAMPAGNA", "CODICE_PREMIO", "CUAA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
