ALTER TABLE DEMETRA.DMT_T_ANAGRAFICA_ALLEV MODIFY TIPO_ALLEV_COD varchar2(10 char);

ALTER TABLE DEMETRA.DMT_T_ANAGRAFICA_ALLEV MODIFY TIPO_ALLEV_DESCR varchar2(50 char);

ALTER TABLE DEMETRA.DMT_T_ANAGRAFICA_ALLEV MODIFY TIPO_PRODUZIONE varchar2(30 char);
