CREATE TABLE DEMETRA.CUAA_SCARICO_MANUALE 
(	
    ANNO_CAMPAGNA NUMBER(4,0) NOT NULL ENABLE, 
    CODICE_PREMIO VARCHAR2(3 CHAR) NOT NULL ENABLE, 
    CUAA VARCHAR2(16 CHAR) NOT NULL ENABLE, 
    CODICE_MISURA VARCHAR2(3 CHAR) NOT NULL ENABLE, 
    DENOMINAZIONE VARCHAR2(50 CHAR), 
    DESCRIZIONE VARCHAR2(255 CHAR), 
    EXT_ID_AZIENDA NUMBER(10,0), 
    ID_FASE_AVANZAMENTO NUMBER(10,0), 
    ID_PRATICA NUMBER(10,0), 
    ID_STATO_PRATICA NUMBER(10,0), 
    IDENTIFICATIVO NUMBER(19,0), 
    TIPO_FASE NUMBER(10,0), 
    GIORNI_RITARDO NUMBER(19,0), 
    CONSTRAINT PK_CUAA_SCA_MANUALE PRIMARY KEY (ANNO_CAMPAGNA, CODICE_PREMIO, CUAA)
);