--------------------------------------------------------
--  File creato - mercoledì-giugno-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DMT_T_CONTROLLI_SSVV
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_CONTROLLI_SSVV" 
   (	"CGO6_CGO7_CGO8" VARCHAR2(10 CHAR), 
	"COD_FISCALE_PROP" VARCHAR2(16 CHAR), 
	"ANOMALIA_MIN" VARCHAR2(255 CHAR), 
	"AZIENDA_COD" VARCHAR2(12 CHAR), 
	"COD_FISCALE_DETEN" VARCHAR2(16 CHAR), 
	"COD_IRREGOLARITA" NUMBER(10,0), 
	"DETEN_BENEFICIARI" VARCHAR2(16 CHAR), 
	"DETTAGLIO_IRREGOLARITA" VARCHAR2(255 CHAR), 
	"DT_CONTROLLO" TIMESTAMP (6), 
	"DT_VERIFICA" TIMESTAMP (6), 
	"ESITO_VERIFICA" VARCHAR2(255 CHAR), 
	"FLAG_CAPI_PRESENTI_CONTROLLATI" NUMBER(1,0), 
	"GRUPPO_ANOMALIA" VARCHAR2(255 CHAR), 
	"INCIDENZA_CAPI_ANOMALI" NUMBER(10,0), 
	"IRREGOLARITA_RISCONTRATA" VARCHAR2(255 CHAR), 
	"NUM_CAPI_ANOMALI" NUMBER(10,0), 
	"NUM_CAPI_ANOMALI_PROPORZIONE" NUMBER(*,2), 
	"NUM_CAPI_CONFORMI" NUMBER(10,0), 
	"NUM_CAPI_CONTROLLATI" NUMBER(10,0), 
	"NUM_CAPI_PRESENTI" NUMBER(10,0), 
	"NUM_IRREGOLARITA" NUMBER(10,0), 
	"PARAMETRI_VALUTAZIONE" NUMBER(10,0), 
	"PROPR_BENEFICIARI" VARCHAR2(16 CHAR), 
	"SPECIE_ALLEVATA" VARCHAR2(25 CHAR)
   ) SEGMENT CREATION DEFERRED 

  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_CONTROLLI_SSVV
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_CONTROLLI_SSVV" ON "DEMETRA"."DMT_T_CONTROLLI_SSVV" ("CGO6_CGO7_CGO8", "COD_FISCALE_PROP") 

  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_CONTROLLI_SSVV
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_CONTROLLI_SSVV" MODIFY ("CGO6_CGO7_CGO8" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_CONTROLLI_SSVV" MODIFY ("COD_FISCALE_PROP" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_CONTROLLI_SSVV" ADD CONSTRAINT "PK_DMT_T_CONTROLLI_SSVV" PRIMARY KEY ("CGO6_CGO7_CGO8", "COD_FISCALE_PROP");
