--------------------------------------------------------
--  File creato - mercoledì-giugno-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DROP Table DMT_T_TWS_BDN_DU_CAPI_OVICA
--------------------------------------------------------

  DROP TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA";

--------------------------------------------------------
--  DDL for Table DMT_T_TWS_BDN_DU_CAPI_OVICA
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" 
   (	"ID_AUTOGENERATO" NUMBER(19,0), 
	"ID_ALLEVAMENTO" NUMBER(19,0), 
	"COD_AZIENDA" VARCHAR2(16 CHAR), 
	"ID_CAPO" NUMBER(19,0), 
	"CODICE" VARCHAR2(16 CHAR), 
	"CODICE_PREMIO" VARCHAR2(3 CHAR), 
	"CONS_MEDIA" FLOAT(126), 
	"CUAA" VARCHAR2(16 CHAR), 
	"DATA_APPL_MARCHIO" DATE, 
	"DATA_COM_MACELLAZIONE" DATE, 
	"DATA_COM_NASCITA" DATE, 
	"DATA_FINE_DETENZIONE" DATE, 
	"DATA_INIZIO_DETENZIONE" DATE, 
	"DATA_INSERIMENTO_BDN_NASCITA" DATE, 
	"DATA_MACELLAZIONE" DATE, 
	"DATA_NASCITA" DATE, 
	"DATA_REGISTR_MACELL" DATE, 
	"DATA_ULTIMO_PREL_PROFILASSI" DATE, 
	"FLAG_DELEGATO_NASCITA" VARCHAR2(1 CHAR), 
	"GENOTIPO" VARCHAR2(50 CHAR), 
	"COD_RAZZA" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_NASCITA" VARCHAR2(3 CHAR), 
	"SESSO" VARCHAR2(1 CHAR), 
	"FK_DMT_D_CLS_PREM_VALID" NUMBER(19,0), 
	"ID_SESSIONE" NUMBER(19,0)
   )

  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_TWS_BDN_DU_CAPI_OVICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_TWS_BDN_DU_CAPI_OVICA" ON "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" ("ID_AUTOGENERATO") 
 
  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_TWS_BDN_DU_CAPI_OVICA
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" MODIFY ("ID_AUTOGENERATO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" MODIFY ("ID_ALLEVAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" MODIFY ("ID_CAPO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" MODIFY ("CODICE_PREMIO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" ADD CONSTRAINT "PK_DMT_T_TWS_BDN_DU_CAPI_OVICA" PRIMARY KEY ("ID_AUTOGENERATO");
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_TWS_BDN_DU_CAPI_OVICA
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" ADD CONSTRAINT "FK_DMT_D_CLS_PREM_VAL_RESP_03" FOREIGN KEY ("FK_DMT_D_CLS_PREM_VALID")
	  REFERENCES "DEMETRA"."DMT_D_CLS_PREMIO_VAL_RESP" ("ID_AUTOGENERATO") ENABLE;
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_OVICA" ADD CONSTRAINT "FK_DMT_T_SESSIONE_15" FOREIGN KEY ("ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
