--------------------------------------------------------
--  File creato - mercoledì-giugno-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DROP Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  DROP TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI";

--------------------------------------------------------
--  DDL for Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" 
   (	"ID_AUTOGENERATO" NUMBER(19,0), 
	"AZIENDA_CODICE" VARCHAR2(12 CHAR), 
	"C_CAPI_TOT" NUMBER(19,2), 
	"C_CAPRETTI_MAC_TOT" NUMBER(19,2), 
	"C_FEMMINE_ADULTE" NUMBER(19,2), 
	"C_FEMMINE_ADULTE_LIB" NUMBER(19,2), 
	"C_FEMMINE_RIMONTA" NUMBER(19,2), 
	"C_FEMMINE_RIMONTA_LIB" NUMBER(19,2), 
	"C_MASCHI_ADULTI" NUMBER(19,2), 
	"C_MASCHI_ADULTI_LIB" NUMBER(19,2), 
	"C_MASCHI_RIMONTA" NUMBER(19,2), 
	"C_MASCHI_RIMONTA_LIB" NUMBER(19,2), 
	"CENSIMENTO_ID" NUMBER(19,2), 
	"COD_FISCALE_DETE" VARCHAR2(16 CHAR), 
	"COD_FISCALE_PROP" VARCHAR2(16 CHAR), 
	"CODICE_QUALIFICA_SCRAPIE" VARCHAR2(10 CHAR), 
	"DATA_CENSIMENTO" DATE, 
	"DATA_FINE_PERIODO" DATE, 
	"DATA_INIZIO_PERIODO" DATE, 
	"DATA_RILEVAZIONE_QUALIFICA" DATE, 
	"DESCR_QUALIFICA_SCRAPIE" VARCHAR2(255 CHAR), 
	"DT_COM_AUTORITA" DATE, 
	"O_AGNELLI_MAC_TOT" NUMBER(19,2), 
	"O_CAPI_TOT" NUMBER(19,2), 
	"O_FEMMINE_ADULTE" NUMBER(19,2), 
	"O_FEMMINE_ADULTE_LIB" NUMBER(19,2), 
	"O_FEMMINE_RIMONTA" NUMBER(19,2), 
	"O_FEMMINE_RIMONTA_LIB" NUMBER(19,2), 
	"O_MASCHI_ADULTI" NUMBER(19,2), 
	"O_MASCHI_ADULTI_LIB" NUMBER(19,2), 
	"O_MASCHI_RIMONTA" NUMBER(19,2), 
	"O_MASCHI_RIMONTA_LIB" NUMBER(19,2), 
	"P_ALLEV_ID" NUMBER(19,2), 
	"SPECIE_CODICE" VARCHAR2(25 CHAR), 
	"SPECIE_DESCRIZIONE" VARCHAR2(255 CHAR), 
	"ID_SESSIONE" NUMBER(19,0)
   )

  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_UBA_CENS_AL_OV" ON "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" ("ID_AUTOGENERATO") 

  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("ID_AUTOGENERATO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("CENSIMENTO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("P_ALLEV_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" ADD CONSTRAINT "PK_DMT_T_UBA_CENS_AL_OV" PRIMARY KEY ("ID_AUTOGENERATO");
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_UBA_CENSIM_ALLEV_OVINI
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_UBA_CENSIM_ALLEV_OVINI" ADD CONSTRAINT "FK_DMT_T_SESSIONE_16" FOREIGN KEY ("ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
