--------------------------------------------------------
--  File creato - mercoledì-giugno-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DROP for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  DROP TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV";

--------------------------------------------------------
--  DDL for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  CREATE TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" 
   (	"ID_AUTOGENERATO" NUMBER(19,0), 
	"ID_ALLEVAMENTO" NUMBER(19,0), 
	"COD_AZIENDA" VARCHAR2(12 CHAR), 
	"AZIENDA_LATITUDINE" NUMBER(11,6), 
	"AZIENDA_LONGITUDINE" NUMBER(11,6), 
	"ID_CAPO" NUMBER(19,0), 
	"COD_LIBRO" VARCHAR2(3 CHAR), 
	"CODICE" VARCHAR2(16 CHAR), 
	"CODICE_PREMIO" VARCHAR2(3 CHAR), 
	"CODICE_VITELLO" VARCHAR2(16 CHAR), 
	"CUAA" VARCHAR2(16 CHAR), 
	"DATA_NASCITA" DATE, 
	"DESCR_LIBRO" VARCHAR2(255 CHAR), 
	"DATA_FINE_DETENZIONE" DATE, 
	"DATA_INIZIO_DETENZIONE" DATE, 
	"DATA_NASCITA_VITELLO" DATE, 
	"FLAG_DELEGATO" VARCHAR2(10 CHAR), 
	"FLAG_DELEGATO_INGRESSO_VACCA" VARCHAR2(1 CHAR), 
	"FLAG_DELEGATO_INGRESSO_VITELLO" VARCHAR2(1 CHAR), 
	"FLAG_DELEGATO_NASCITA_VITELLO" VARCHAR2(1 CHAR), 
	"FLAG_IBR" VARCHAR2(1 CHAR), 
	"FLAG_PROROGA_MARCATURA" VARCHAR2(1 CHAR), 
	"FLAG_RISPETTO_PREVALENZA_IBR" VARCHAR2(10 CHAR), 
	"COD_RAZZA" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_INGR_VACCA" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_INGR_VITELLO" VARCHAR2(3 CHAR), 
	"RUOLO_UTENTE_NASC_VITELLO" VARCHAR2(3 CHAR), 
	"SESSO" VARCHAR2(1 CHAR), 
	"SESSO_VITELLO" VARCHAR2(1 CHAR), 
	"VACCA_DATA_COM_AUT_INGRESSO" DATE, 
	"VACCA_DATA_INGRESSO" DATE, 
	"VACCA_DATA_INSER_BDN_INGRESSO" DATE, 
	"VITELLO_CAPO_ID" NUMBER(19,0), 
	"VITELLO_DATA_APPL_MARCHIO" DATE, 
	"VITELLO_DATA_COM_AUT_INGRESSO" DATE, 
	"VITELLO_DATA_COM_AUT_NASCITA" DATE, 
	"VITELLO_DATA_INSER_BDN_NASCITA" DATE, 
	"VITELLO_TIPO_ORIGINE" VARCHAR2(1 CHAR), 
	"VITELLO_DATA_INS_BDN_INGRESSO" DATE, 
	"FK_DMT_D_CLS_PREM_VALID" NUMBER(19,0), 
	"ID_SESSIONE" NUMBER(19,0)
   )

  TABLESPACE "DEMETRA_TBL" ;
--------------------------------------------------------
--  DDL for Index IE_DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMETRA"."IE_DMT_T_TWS_BDN_DU_CAPI_BOV" ON "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ("ID_AUTOGENERATO") 

  TABLESPACE "DEMETRA_IDX" ;
--------------------------------------------------------
--  Constraints for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("ID_AUTOGENERATO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("ID_ALLEVAMENTO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("ID_CAPO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("CODICE_PREMIO" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" MODIFY ("ID_SESSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ADD CONSTRAINT "PK_DMT_T_TWS_BDN_DU_CAP_BOV" PRIMARY KEY ("ID_AUTOGENERATO");
--------------------------------------------------------
--  Ref Constraints for Table DMT_T_TWS_BDN_DU_CAPI_BOV
--------------------------------------------------------

  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ADD CONSTRAINT "FK_DMT_T_SESSIONE_14" FOREIGN KEY ("ID_SESSIONE")
	  REFERENCES "DEMETRA"."DMT_T_SESSIONE" ("ID_SESSIONE") ENABLE;
 
  ALTER TABLE "DEMETRA"."DMT_T_TWS_BDN_DU_CAPI_BOV" ADD CONSTRAINT "FK_DMT_D_CLS_PREM_VAL_RESP_02" FOREIGN KEY ("FK_DMT_D_CLS_PREM_VALID")
	  REFERENCES "DEMETRA"."DMT_D_CLS_PREMIO_VAL_RESP" ("ID_AUTOGENERATO") ENABLE;
